### PR TITLE
[TECH-38] Install yt-dlp and update requirements.txt

### PR DESCRIPTION
**Pull request by peach3es**
Install the packages needed to start implementing ringtone being able to be set with YT url

### CODE REVIEW

**Comment by maxxfreund** [comment]
question for you my sweet lad @peach3es 

image

Does the list of cogs need to updated to inclue the cogs.ytRequest or am I misunderstanding?

**Comment by peach3es** [comment]
> question for you my sweet lad @peach3es
> 
> image
> 
> Does the list of cogs need to updated to inclue the cogs.ytRequest or am I misunderstanding?

When the file contains discord related commands or other functions, cogs needs to be used. ytRequest.py is just a file that holds a function to send api request for downloading youtube videos which doesn't really need cogs. I'm simply just importing that function in the timer.py. it's not being used in the main.py

If I had made another file for a different discord command to be implemented, then I would need to specify it in the main.py in that extension list.

**Review by maxxfreund — APPROVED** [review]
yippee 💯 bro set this up for an alleyoop

**Review by maxxfreund — APPROVED** [review]
image

**Review by maxxfreund — APPROVED** [review]
Bros making the changes before i can even review tf

**Review by maxxfreund — APPROVED** [review]
peer reviewed the 💩 outta this ong

**Review by maxxfreund — APPROVED** [review]
prevents nsfw links to work lol,, good job

**Pull request merged**
